name: Unittest

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run:
    environment: SVN
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.0']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }} with PHP version {{ matrix.php-versions }}
    steps:
    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '5.7'
        mysql database: 'wordpress_test'
        mysql root password: ${{ secrets.RootPassword }}
        mysql user: 'developer'
        mysql password: '123456'

    - name: Checkout from GIT
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, mysqli, intl, curl #optional, setup extensions
        ini-values: post_max_size=256M, short_open_tag=On #optional, setup php.ini configuration
        coverage: xdebug #optional, setup coverage driver
        tools: php-cs-fixer, phpunit

    - name: Check PHP Version
      run: php -v

    - name: Install WP Tests
      run: bash bin/install-wp-tests.sh wordpress_test developer '123456' 172.17.0.1 latest