name: Release

# Controls when the action will run.
on:
  push:
    # Pattern matched against refs/tags
    tags:
    - '*'           # Push events to every tag

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deployment to WP SVN (tag only)
    steps:
    - name: Checkout from GIT
      uses: actions/checkout@v2

    - name: Set env
        run: echo "TRAVIS_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Run svn commit script
      run: |
        echo $TRAVIS_TAG
        sh bin/install-wp-tests.sh $TRAVIS_TAG --stable > /dev/null
      env:
        SVNURL: ${{ secrets.SVNURL }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USER: ${{ secrets.SVN_USER }}
        TRAVIS_TAG: ${{ env.TRAVIS_TAG }}